/**
 * Render benchmark results as charts.
 *
 * Dependency-free on purpose: SVG is generated by hand so the output needs no
 * CDN, no headless browser, and no charting library, and so the numbers can be
 * traced straight from the results file to the pixels.
 *
 * Exports `renderCharts()` for `scripts/dashboard.mjs`, and writes standalone
 * .svg files plus an index when run directly:
 *
 *   node scripts/charts.mjs results/bench-final.rescored.json
 *                            [--out results/charts] [--png]
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const FIELDS = [
  ['merchant', 'merchant'],
  ['date', 'date'],
  ['total', 'total'],
  ['currency', 'currency'],
  ['tax', 'tax'],
  ['line_items', 'line items'],
];

const PALETTE = {
  accent: '#4f8ef7',
  accentDim: '#2b4a7d',
  good: '#4caf7d',
  mid: '#e0a33e',
  bad: '#d9534f',
  grid: '#2c313c',
  axis: '#5a616e',
  text: '#d7dae0',
  textDim: '#9aa0a6',
  bg: '#12151b',
  panel: '#181c24',
};

const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const pct = (x) => `${(x * 100).toFixed(1)}%`;
const pct0 = (x) => `${Math.round(x * 100)}%`;

/** Red -> amber -> green, for heatmaps. */
function heatColor(v) {
  const stops = [
    [0.0, [190, 70, 65]],
    [0.5, [224, 163, 62]],
    [1.0, [76, 175, 125]],
  ];
  let a = stops[0];
  let b = stops[stops.length - 1];
  for (let i = 0; i < stops.length - 1; i++) {
    if (v >= stops[i][0] && v <= stops[i + 1][0]) { a = stops[i]; b = stops[i + 1]; break; }
  }
  const t = b[0] === a[0] ? 0 : (v - a[0]) / (b[0] - a[0]);
  const c = a[1].map((x, i) => Math.round(x + (b[1][i] - x) * t));
  return `rgb(${c[0]},${c[1]},${c[2]})`;
}

const svgOpen = (w, h, title) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" aria-label="${esc(title)}" font-family="ui-sans-serif, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif">\n` +
  `<rect width="${w}" height="${h}" fill="${PALETTE.bg}"/>\n`;

function axisLabel(x, y, text, opts = {}) {
  return `<text x="${x}" y="${y}" fill="${opts.fill ?? PALETTE.textDim}" font-size="${opts.size ?? 12}" text-anchor="${opts.anchor ?? 'start'}"${opts.weight ? ` font-weight="${opts.weight}"` : ''}>${esc(text)}</text>\n`;
}

// ---------------------------------------------------------------- chart 1 ----
/** Main comparison: headline accuracy with JSON-validity and exact-match overlays. */
function chartAccuracy(models) {
  const W = 900;
  const rowH = 104;
  const top = 70;
  const H = top + models.length * rowH + 44;
  const left = 150;
  const right = 78;
  const plotW = W - left - right;

  let s = svgOpen(W, H, 'Headline accuracy by model');
  s += axisLabel(24, 32, 'Headline accuracy', { fill: PALETTE.text, size: 17, weight: 600 });
  s += axisLabel(24, 50, 'merchant + date + total + currency, averaged over 24 receipts', { size: 12 });

  for (let t = 0; t <= 1.0001; t += 0.25) {
    const x = left + t * plotW;
    s += `<line x1="${x}" y1="${top - 10}" x2="${x}" y2="${H - 38}" stroke="${PALETTE.grid}" stroke-width="1"/>\n`;
    s += axisLabel(x, H - 20, pct0(t), { anchor: 'middle', size: 11 });
  }

  models.forEach((m, i) => {
    const y = top + i * rowH;
    const acc = m.summary.accuracy;
    const w = Math.max(2, acc * plotW);
    const isWinner = i === 0;

    s += axisLabel(left - 14, y + 18, m.short, { anchor: 'end', fill: PALETTE.text, size: 13, weight: isWinner ? 600 : 400 });
    s += axisLabel(left - 14, y + 34, m.dtype, { anchor: 'end', size: 11 });

    // Main accuracy bar.
    s += `<rect x="${left}" y="${y + 2}" width="${plotW}" height="28" rx="4" fill="${PALETTE.panel}"/>\n`;
    s += `<rect x="${left}" y="${y + 2}" width="${w.toFixed(1)}" height="28" rx="4" fill="${heatColor(acc)}"/>\n`;
    s += axisLabel(left + w + 9, y + 21, pct(acc), { fill: PALETTE.text, size: 13, weight: 600 });

    // Secondary metrics as slim labelled bars, spaced clear of the main bar.
    const sub = [
      ['JSON valid', m.summary.jsonParseRate, PALETTE.accent],
      ['exact match', m.summary.exactMatchRate, PALETTE.accentDim],
    ];
    sub.forEach(([label, v], k) => {
      const sy = y + 42 + k * 20;
      const sw = Math.max(1, v * plotW);
      s += axisLabel(left - 14, sy + 9, label, { anchor: 'end', size: 10 });
      s += `<rect x="${left}" y="${sy}" width="${plotW}" height="11" rx="2" fill="${PALETTE.panel}"/>\n`;
      s += `<rect x="${left}" y="${sy}" width="${sw.toFixed(1)}" height="11" rx="2" fill="${sub[k][2]}"/>\n`;
      s += axisLabel(left + plotW + 9, sy + 9, pct0(v), { size: 10 });
    });
  });

  s += '</svg>';
  return s;
}

// ---------------------------------------------------------------- chart 2 ----
/** Per-field heatmap. This is the chart that should drive a model choice. */
function chartFieldHeatmap(models) {
  const W = 900;
  const cellW = 108;
  const cellH = 54;
  const left = 150;
  const top = 96;
  const H = top + models.length * cellH + 48;

  let s = svgOpen(W, H, 'Per-field accuracy heatmap');
  s += axisLabel(24, 32, 'Per-field accuracy', { fill: PALETTE.text, size: 17, weight: 600 });
  s += axisLabel(24, 50, 'Aggregate scores hide which field a model actually fails on', { size: 12 });
  s += axisLabel(24, 72, 'total and line items are the weakest fields for every model measured', { size: 12, fill: PALETTE.textDim });

  FIELDS.forEach(([, label], j) => {
    s += axisLabel(left + j * cellW + cellW / 2, top - 12, label, { anchor: 'middle', size: 12, fill: PALETTE.text });
  });

  models.forEach((m, i) => {
    const y = top + i * cellH;
    s += axisLabel(left - 14, y + cellH / 2 + 5, m.short, { anchor: 'end', fill: PALETTE.text, size: 13 });
    FIELDS.forEach(([key], j) => {
      const v = m.summary.fieldAccuracy?.[key] ?? 0;
      const x = left + j * cellW;
      s += `<rect x="${x + 3}" y="${y + 3}" width="${cellW - 6}" height="${cellH - 6}" rx="5" fill="${heatColor(v)}" opacity="0.92"/>\n`;
      const txt = v < 0.06 ? PALETTE.text : '#0d1017';
      s += axisLabel(x + cellW / 2, y + cellH / 2 + 5, pct0(v), { anchor: 'middle', size: 13, fill: txt, weight: 600 });
    });
  });

  s += axisLabel(24, H - 16, 'Every model fails on total. The 256M tier scores 0% — it concatenates the receipt number and VAT id into the total.', { size: 11, fill: PALETTE.textDim });
  s += '</svg>';
  return s;
}

// ---------------------------------------------------------------- chart 3 ----
/** Accuracy vs latency, bubble area = download size. */
function chartTradeoff(models) {
  const W = 900;
  const H = 580;
  const left = 88;
  const right = 214;
  const top = 64;
  const bottom = 78;
  const plotW = W - left - right;
  const plotH = H - top - bottom;

  let s = svgOpen(W, H, 'Accuracy versus latency');
  s += axisLabel(24, 32, 'Accuracy vs. latency', { fill: PALETTE.text, size: 17, weight: 600 });
  s += axisLabel(24, 50, 'Up and to the left is better. Bubble area = model download size.', { size: 12 });

  const accs = models.map((m) => m.summary.accuracy);
  const lats = models.map((m) => m.summary.latencyMs.p50 / 1000);
  const accMin = Math.max(0, Math.floor(Math.min(...accs) * 10) / 10 - 0.08);
  const accMax = Math.min(1, Math.ceil(Math.max(...accs) * 10) / 10 + 0.08);
  const latMin = 0;
  const latMax = Math.ceil(Math.max(...lats)) + 1;

  const X = (lat) => left + ((lat - latMin) / (latMax - latMin)) * plotW;
  const Y = (acc) => top + plotH - ((acc - accMin) / (accMax - accMin)) * plotH;

  for (let a = accMin; a <= accMax + 1e-9; a += 0.1) {
    const y = Y(a);
    s += `<line x1="${left}" y1="${y}" x2="${left + plotW}" y2="${y}" stroke="${PALETTE.grid}"/>\n`;
    s += axisLabel(left - 12, y + 4, pct0(a), { anchor: 'end', size: 11 });
  }
  for (let l = latMin; l <= latMax; l += 2) {
    const x = X(l);
    s += `<line x1="${x}" y1="${top}" x2="${x}" y2="${top + plotH}" stroke="${PALETTE.grid}"/>\n`;
    s += axisLabel(x, top + plotH + 22, `${l}s`, { anchor: 'middle', size: 11 });
  }
  s += axisLabel(left + plotW / 2, top + plotH + 48, 'median generation time per receipt', { anchor: 'middle', size: 12, fill: PALETTE.text });
  s += `<text x="26" y="${top + plotH / 2}" fill="${PALETTE.text}" font-size="12" text-anchor="middle" transform="rotate(-90 26 ${top + plotH / 2})">headline accuracy</text>\n`;

  s += `<path d="M ${left + 16} ${top + 30} L ${left + 16} ${top + 12} L ${left + 34} ${top + 12}" fill="none" stroke="${PALETTE.axis}" stroke-width="1.5" stroke-dasharray="3 3"/>\n`;
  s += axisLabel(left + 40, top + 17, 'better', { size: 11, fill: PALETTE.textDim });

  const dl = models.map((m) => m.load.downloadBytes / 1048576);
  const dlMin = Math.min(...dl);
  const dlMax = Math.max(...dl);
  const radiusFor = (mb) => 15 + 15 * Math.sqrt((mb - dlMin) / Math.max(1, dlMax - dlMin));

  // Markers first, then every label in a second pass, so no bubble is drawn over
  // a label. Labels sit outside the bubbles with a halo, because text inside a
  // small bubble collides with the gridlines and becomes unreadable.
  const placed = models.map((m) => ({
    m,
    cx: X(m.summary.latencyMs.p50 / 1000),
    cy: Y(m.summary.accuracy),
    r: radiusFor(m.load.downloadBytes / 1048576),
  }));

  for (const p of placed) {
    const d = p.m.summary.accuracy;
    // The winner is filled solid; the rest are translucent. Two bubbles can sit
    // almost on top of each other (both 500M variants), and without this the one
    // drawn last completely hides the other.
    const isWinner = p.m === models[0];
    s += `<circle cx="${p.cx.toFixed(1)}" cy="${p.cy.toFixed(1)}" r="${p.r.toFixed(1)}" fill="${heatColor(d)}" opacity="${isWinner ? 0.85 : 0.32}" stroke="${heatColor(d)}" stroke-width="${isWinner ? 2.5 : 1.5}"/>\n`;
  }
  for (const p of placed) {
    // Winner label above, everyone else below: the two 500M bubbles are close
    // enough in accuracy that both labels would otherwise land on each other.
    const isWinner = p.m === models[0];
    const ly = isWinner ? p.cy - p.r - 20 : p.cy + p.r + 16;
    const weight = isWinner ? 600 : 400;
    s += `<text x="${p.cx.toFixed(1)}" y="${ly.toFixed(1)}" fill="${PALETTE.text}" font-size="12" font-weight="${weight}" text-anchor="middle" stroke="${PALETTE.bg}" stroke-width="4" paint-order="stroke">${esc(p.m.short)}</text>\n`;
    s += `<text x="${p.cx.toFixed(1)}" y="${(ly + 14).toFixed(1)}" fill="${PALETTE.textDim}" font-size="11" text-anchor="middle" stroke="${PALETTE.bg}" stroke-width="4" paint-order="stroke">${pct0(p.m.summary.accuracy)} @ ${(p.m.summary.latencyMs.p50 / 1000).toFixed(1)}s</text>\n`;
  }

  const lx = left + plotW + 30;
  let ly = top + 8;
  s += axisLabel(lx, ly, 'download size', { size: 12, fill: PALETTE.text, weight: 600 });
  ly += 24;
  [dlMin, (dlMin + dlMax) / 2, dlMax].forEach((mb) => {
    const r = radiusFor(mb);
    s += `<circle cx="${lx + r}" cy="${ly}" r="${r.toFixed(1)}" fill="none" stroke="${PALETTE.axis}"/>\n`;
    s += axisLabel(lx + 2 * r + 10, ly + 4, `${Math.round(mb)} MB`, { size: 11 });
    ly += 2 * r + 12;
  });
  ly += 16;
  s += axisLabel(lx, ly, 'accuracy', { size: 12, fill: PALETTE.text, weight: 600 });
  ly += 20;
  [[1.0, 'high'], [0.5, 'mid'], [0.0, 'low']].forEach(([v, label]) => {
    s += `<rect x="${lx}" y="${ly - 10}" width="16" height="12" rx="3" fill="${heatColor(v)}"/>\n`;
    s += axisLabel(lx + 24, ly, label, { size: 11 });
    ly += 20;
  });

  s += '</svg>';
  return s;
}

// ---------------------------------------------------------------- chart 4 ----
/** How each model's output was recovered. Shows strict parsing alone understates quality. */
function chartParseStrategy(models) {
  const W = 900;
  const H = 260;
  const left = 150;
  const top = 84;
  const plotW = W - left - 60;
  const rowH = 46;

  const ORDER = [
    ['direct', 'clean JSON', PALETTE.good],
    ['truncated-salvage', 'truncated, recovered', PALETTE.mid],
    ['field-salvage', 'broken JSON, fields recovered', PALETTE.bad],
    ['unparseable', 'unrecoverable', '#6b7280'],
  ];

  let s = svgOpen(W, H, 'How output was recovered');
  s += axisLabel(24, 32, 'How each model’s output was recovered', { fill: PALETTE.text, size: 17, weight: 600 });
  s += axisLabel(24, 50, 'Counts per 24 receipts. Treating broken JSON as a total loss understated every model.', { size: 12 });

  const total = (m) => Object.values(m.summary.parseStrategies ?? {}).reduce((a, b) => a + b, 0) || 1;

  models.forEach((m, i) => {
    const y = top + i * rowH;
    s += axisLabel(left - 14, y + 20, m.short, { anchor: 'end', fill: PALETTE.text, size: 13 });
    let x = left;
    for (const [key, , color] of ORDER) {
      const n = m.summary.parseStrategies?.[key] ?? 0;
      if (!n) continue;
      const w = (n / total(m)) * plotW;
      s += `<rect x="${x.toFixed(1)}" y="${y + 6}" width="${w.toFixed(1)}" height="26" fill="${color}"/>\n`;
      if (w > 26) s += axisLabel(x + w / 2, y + 24, String(n), { anchor: 'middle', size: 12, fill: '#0d1017', weight: 600 });
      x += w;
    }
  });

  // Legend
  let lx = left;
  const ly = H - 26;
  for (const [, label, color] of ORDER) {
    s += `<rect x="${lx}" y="${ly - 11}" width="13" height="13" rx="3" fill="${color}"/>\n`;
    s += axisLabel(lx + 19, ly, label, { size: 11 });
    lx += 26 + label.length * 6.4;
  }

  s += '</svg>';
  return s;
}

// ---------------------------------------------------------------- chart 5 ----
/**
 * Download size vs accuracy — the decision the PWA actually faces.
 *
 * This is the chart the product owner needs: in a browser tab the one-time
 * download is the cost the user pays before seeing any value, and it is the
 * constraint that disqualifies otherwise-good candidates.
 */
function chartDownloadCost(models) {
  const W = 900;
  const H = 470;
  const left = 96;
  const right = 250;
  const top = 70;
  const bottom = 74;
  const plotW = W - left - right;
  const plotH = H - top - bottom;

  let s = svgOpen(W, H, 'Accuracy versus download size');
  s += axisLabel(24, 32, 'What the user pays vs. what they get', { fill: PALETTE.text, size: 17, weight: 600 });
  s += axisLabel(24, 50, 'One-time model download against headline accuracy. Up and to the left is better.', { size: 12 });

  const xs = models.map((m) => m.load.downloadBytes / 1048576);
  const ys = models.map((m) => m.summary.accuracy);
  const xMin = 0;
  const xMax = Math.max(...xs) * 1.24;
  // Scale to the data instead of a fixed 0..100%: with accuracies clustered
  // between 22% and 63%, a full-height axis buries every point in the lower
  // third and forces the labels to overlap.
  const yMax = Math.min(1, Math.max(...ys) * 1.15);
  const yMin = 0;

  const X = (mb) => left + (mb / xMax) * plotW;
  const Y = (a) => top + plotH - ((a - yMin) / (yMax - yMin)) * plotH;

  for (let a = yMin; a <= yMax + 1e-9; a += 0.1) {
    const y = Y(a);
    s += `<line x1="${left}" y1="${y}" x2="${left + plotW}" y2="${y}" stroke="${PALETTE.grid}"/>\n`;
    s += axisLabel(left - 12, y + 4, pct0(a), { anchor: 'end', size: 11 });
  }
  for (let mb = 0; mb <= xMax; mb += 100) {
    const x = X(mb);
    s += `<line x1="${x}" y1="${top}" x2="${x}" y2="${top + plotH}" stroke="${PALETTE.grid}"/>\n`;
    s += axisLabel(x, top + plotH + 22, `${mb}`, { anchor: 'middle', size: 11 });
  }
  s += axisLabel(left, top + plotH + 46, 'model download (MB)', { size: 12, fill: PALETTE.text });
  s += `<text x="28" y="${top + plotH / 2}" fill="${PALETTE.text}" font-size="12" text-anchor="middle" transform="rotate(-90 28 ${top + plotH / 2})">headline accuracy</text>\n`;

  // 500 MB reference line: a plausible ceiling for a mobile first-load.
  const ref = 500;
  if (ref < xMax) {
    s += `<line x1="${X(ref)}" y1="${top}" x2="${X(ref)}" y2="${top + plotH}" stroke="${PALETTE.mid}" stroke-width="1.5" stroke-dasharray="5 4"/>\n`;
    s += axisLabel(X(ref) + 6, top + 14, '500 MB', { size: 11, fill: PALETTE.mid });
  }

  const placed = models.map((m) => ({
    m,
    cx: X(m.load.downloadBytes / 1048576),
    cy: Y(m.summary.accuracy),
  }));
  for (const p of placed) {
    const isWinner = p.m === models[0];
    s += `<circle cx="${p.cx.toFixed(1)}" cy="${p.cy.toFixed(1)}" r="${isWinner ? 9 : 7}" fill="${heatColor(p.m.summary.accuracy)}" opacity="${isWinner ? 1 : 0.75}" stroke="${PALETTE.bg}" stroke-width="2"/>\n`;
  }

  // The two 256M models sit at nearly the same x AND y, so labels are staggered
  // by accuracy rank rather than all drawn at the marker's own height.
  const ranked = [...placed].sort((a, b) => b.m.summary.accuracy - a.m.summary.accuracy);
  const yOffset = [-8, 10, 24, 38, 52];
  ranked.forEach((p, i) => {
    const isWinner = i === 0;
    const ly = p.cy + (yOffset[i] ?? 40 + (i - 4) * 14);
    s += `<text x="${(p.cx + 15).toFixed(1)}" y="${ly.toFixed(1)}" fill="${PALETTE.text}" font-size="12" font-weight="${isWinner ? 600 : 400}" stroke="${PALETTE.bg}" stroke-width="4" paint-order="stroke">${esc(p.m.short)}  ${pct(p.m.summary.accuracy)} @ ${Math.round(p.m.load.downloadBytes / 1048576)} MB</text>\n`;
  });

  // Cost-per-point note.
  const lx = left + plotW + 26;
  let ly = top + 10;
  s += axisLabel(lx, ly, 'download per point', { size: 12, fill: PALETTE.text, weight: 600 });
  ly += 22;
  for (const m of models) {
    const mb = m.load.downloadBytes / 1048576;
    const cost = mb / Math.max(1, m.summary.accuracy * 100);
    s += axisLabel(lx, ly, `${m.short}: ${cost.toFixed(1)} MB/pt`, { size: 11, fill: PALETTE.textDim });
    ly += 18;
  }

  s += '</svg>';
  return s;
}

// ---------------------------------------------------------------- assemble ---
/**
 * Build every chart for a result file.
 *
 * Exported so `scripts/dashboard.mjs` can inline the same SVG set into a single
 * dashboard rather than the two outputs drifting apart.
 *
 * @param {any} data parsed benchmark result file
 * @returns {Promise<{ charts: {file: string, title: string, svg: string, note: string}[], shortName: (r: any) => string, byAccuracy: any[] }>}
 */
export async function renderCharts(data) {
  const okRuns = (data.runs ?? []).filter((r) => r.status === 'ok' && r.summary);
  const shortName = (r) => {
    const v2 = /VLM2/i.test(r.model);
    return `${v2 ? 'SmolVLM2' : 'SmolVLM'}-${r.params ?? '?'}`;
  };
  const byAccuracy = okRuns
    .map((r) => ({ ...r, short: shortName(r) }))
    .sort((a, b) => b.summary.accuracy - a.summary.accuracy);

  const slowest = [...byAccuracy].sort((a, b) => b.summary.latencyMs.p50 - a.summary.latencyMs.p50)[0];
  const fastest = [...byAccuracy].sort((a, b) => a.summary.latencyMs.p50 - b.summary.latencyMs.p50)[0];
  // Derived, not hardcoded: the winner changed once already, and a stale caption
  // describing a previous result is worse than no caption.
  const tradeoffNote = byAccuracy.length
    ? `Bubble area is download size. Fastest is ${fastest.short} at ${(fastest.summary.latencyMs.p50 / 1000).toFixed(1)}s; ` +
      `slowest is ${slowest.short} at ${(slowest.summary.latencyMs.p50 / 1000).toFixed(1)}s. ` +
      'The smaller models are not reliably faster, and are far less accurate.'
    : 'Bubble area is download size.';

  const charts = [
    { file: 'accuracy.svg', title: 'Headline accuracy', svg: chartAccuracy(byAccuracy), note: 'Primary ranking on the four fields that create a transaction.' },
    { file: 'field-heatmap.svg', title: 'Per-field accuracy', svg: chartFieldHeatmap(byAccuracy), note: 'The chart to choose a model by. Note the total column.' },
    { file: 'tradeoff.svg', title: 'Accuracy vs latency', svg: chartTradeoff(byAccuracy), note: tradeoffNote },
    { file: 'download-cost.svg', title: 'Accuracy vs download size', svg: chartDownloadCost(byAccuracy), note: 'In a browser tab the one-time download is the cost the user pays before seeing any value.' },
    { file: 'parse-strategy.svg', title: 'Output recovery', svg: chartParseStrategy(byAccuracy), note: 'Most failures are structural, not unreadable text.' },
  ];
  return { charts, shortName, byAccuracy };
}

// -------------------------------------------------------------- CLI driver ---
// Only run when invoked directly (`node scripts/charts.mjs ...`); importing this
// module from the dashboard must have no side effects.
const invokedDirectly = process.argv[1] && import.meta.url === `file:///${process.argv[1].replace(/\\/g, '/')}`;

if (invokedDirectly) {
  const input = process.argv.slice(2).find((a) => !a.startsWith('--') && a.endsWith('.json'));
  if (!input) {
    console.error('usage: node scripts/charts.mjs <results.json> [--out results/charts] [--png]');
    process.exit(1);
  }
  const outDir = arg('out', path.join('results', 'charts'));
  const data = JSON.parse(await readFile(input, 'utf8'));
  const { charts } = await renderCharts(data);

  await mkdir(outDir, { recursive: true });
  for (const c of charts) await writeFile(path.join(outDir, c.file), c.svg, 'utf8');

  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>VLM Receipt Benchmark — Charts</title>
<style>
  :root { color-scheme: dark; }
  body { margin:0; padding:2rem 1.25rem 4rem; background:${PALETTE.bg}; color:${PALETTE.text};
         font:15px/1.6 ui-sans-serif, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  main { max-width:960px; margin:0 auto; }
  h1 { font-size:1.5rem; margin:0 0 .35rem; }
  figure { margin:0 0 2.25rem; }
  figcaption { color:${PALETTE.textDim}; font-size:.85rem; margin-top:.5rem; }
  .chart { border:1px solid ${PALETTE.grid}; border-radius:12px; overflow:hidden; }
  .chart svg { display:block; width:100%; height:auto; }
</style></head>
<body><main>
<h1>VLM Receipt Benchmark — Charts</h1>
${charts.map((c) => `<figure><div class="chart">${c.svg}</div><figcaption><strong>${esc(c.title)}</strong> — ${esc(c.note)}</figcaption></figure>`).join('\n')}
</main></body></html>
`;
  const htmlPath = path.join(outDir, 'index.html');
  await writeFile(htmlPath, html, 'utf8');

  console.log(`[charts] wrote ${charts.length} svg + dashboard to ${outDir}`);
  for (const c of charts) console.log(`  ${path.join(outDir, c.file)}`);
  console.log(`  ${htmlPath}`);

  if (process.argv.includes('--png')) {
    const { chromium } = await import('playwright-core');
    const { resolve } = await import('node:path');
    const CHROME = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    const browser = await chromium.launch({
      executablePath: CHROME,
      headless: true,
      args: ['--no-sandbox', '--disable-gpu-sandbox', '--no-first-run', '--disable-crash-reporter'],
    });
    const page = await browser.newPage({ viewport: { width: 1040, height: 1200 }, deviceScaleFactor: 1 });
    await page.goto(`file:///${resolve(htmlPath).replace(/\\/g, '/')}`, { waitUntil: 'load' });
    const png = path.join(outDir, 'dashboard.png');
    await page.screenshot({ path: png, fullPage: true });
    await browser.close();
    console.log(`  ${png}`);
  }
}
